	tetrisNios u0 (
		.clk_clk             (<connected-to-clk_clk>),             //          clk.clk
		.fast_move_export    (<connected-to-fast_move_export>),    //    fast_move.export
		.hex7_export         (<connected-to-hex7_export>),         //         hex7.export
		.hex_0_export        (<connected-to-hex_0_export>),        //        hex_0.export
		.hex_1_export        (<connected-to-hex_1_export>),        //        hex_1.export
		.hex_2_export        (<connected-to-hex_2_export>),        //        hex_2.export
		.hex_3_export        (<connected-to-hex_3_export>),        //        hex_3.export
		.hex_4_export        (<connected-to-hex_4_export>),        //        hex_4.export
		.hex_5_export        (<connected-to-hex_5_export>),        //        hex_5.export
		.hex_6_export        (<connected-to-hex_6_export>),        //        hex_6.export
		.move_left_export    (<connected-to-move_left_export>),    //    move_left.export
		.move_right_export   (<connected-to-move_right_export>),   //   move_right.export
		.reset_reset_n       (<connected-to-reset_reset_n>),       //        reset.reset_n
		.reset_game_export   (<connected-to-reset_game_export>),   //   reset_game.export
		.rotate_left_export  (<connected-to-rotate_left_export>),  //  rotate_left.export
		.rotate_right_export (<connected-to-rotate_right_export>), // rotate_right.export
		.row_0_export        (<connected-to-row_0_export>),        //        row_0.export
		.row_1_export        (<connected-to-row_1_export>),        //        row_1.export
		.row_10_export       (<connected-to-row_10_export>),       //       row_10.export
		.row_11_export       (<connected-to-row_11_export>),       //       row_11.export
		.row_12_export       (<connected-to-row_12_export>),       //       row_12.export
		.row_13_export       (<connected-to-row_13_export>),       //       row_13.export
		.row_14_export       (<connected-to-row_14_export>),       //       row_14.export
		.row_15_export       (<connected-to-row_15_export>),       //       row_15.export
		.row_16_export       (<connected-to-row_16_export>),       //       row_16.export
		.row_17_export       (<connected-to-row_17_export>),       //       row_17.export
		.row_18_export       (<connected-to-row_18_export>),       //       row_18.export
		.row_19_export       (<connected-to-row_19_export>),       //       row_19.export
		.row_2_export        (<connected-to-row_2_export>),        //        row_2.export
		.row_20_export       (<connected-to-row_20_export>),       //       row_20.export
		.row_21_export       (<connected-to-row_21_export>),       //       row_21.export
		.row_22_export       (<connected-to-row_22_export>),       //       row_22.export
		.row_23_export       (<connected-to-row_23_export>),       //       row_23.export
		.row_3_export        (<connected-to-row_3_export>),        //        row_3.export
		.row_4_export        (<connected-to-row_4_export>),        //        row_4.export
		.row_5_export        (<connected-to-row_5_export>),        //        row_5.export
		.row_6_export        (<connected-to-row_6_export>),        //        row_6.export
		.row_7_export        (<connected-to-row_7_export>),        //        row_7.export
		.row_8_export        (<connected-to-row_8_export>),        //        row_8.export
		.row_9_export        (<connected-to-row_9_export>),        //        row_9.export
		.sram_DQ             (<connected-to-sram_DQ>),             //         sram.DQ
		.sram_ADDR           (<connected-to-sram_ADDR>),           //             .ADDR
		.sram_LB_N           (<connected-to-sram_LB_N>),           //             .LB_N
		.sram_UB_N           (<connected-to-sram_UB_N>),           //             .UB_N
		.sram_CE_N           (<connected-to-sram_CE_N>),           //             .CE_N
		.sram_OE_N           (<connected-to-sram_OE_N>),           //             .OE_N
		.sram_WE_N           (<connected-to-sram_WE_N>)            //             .WE_N
	);

